version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - 4000:4000
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=mysql://root:cluz@db:3306/cluz
      - REDIS_URL=redis://redis:6379

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=cluz
      - MYSQL_DATABASE=cluz

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=cluz
      
